"""empty message

Revision ID: 1e9633269657
Revises: 83ff94d2860b
Create Date: 2025-08-06 16:43:07.382555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9633269657'
down_revision = '83ff94d2860b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('game_team')
    with op.batch_alter_table('team_tournament', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('team_tournament', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('game_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('videojuego_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], name='game_team_videojuego_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_team_pkey')
    )
    op.drop_table('team')
    # ### end Alembic commands ###
