"""empty message

Revision ID: 2bd5ff0db82d
Revises: e66b7e8521bd
Create Date: 2025-08-06 07:09:23.409262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd5ff0db82d'
down_revision = 'e66b7e8521bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
