"""empty message

Revision ID: 2fac01ca8498
Revises: aa87655865c8
Create Date: 2025-07-31 17:48:48.594959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fac01ca8498'
down_revision = 'aa87655865c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using="prize::integer",
               existing_nullable=False)
        batch_op.alter_column('prize',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using="prize::integer",
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('prize',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
