"""empty message

Revision ID: 408f8c3d3565
Revises: a1e21aef582e
Create Date: 2025-07-26 17:56:20.074847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408f8c3d3565'
down_revision = 'a1e21aef582e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('prize', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    # ### end Alembic commands ###
