"""empty message

Revision ID: 447dd214d1f6
Revises: 7acadd43e23e
Create Date: 2025-08-06 12:05:31.111635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447dd214d1f6'
down_revision = '7acadd43e23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
