"""empty message

Revision ID: 4637603fb408
Revises: 1da08f9a29f8
Create Date: 2025-08-06 06:59:33.709590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4637603fb408'
down_revision = '1da08f9a29f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_videojuego', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_videojuego', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
