"""empty message

Revision ID: 4c8e89f994fb
Revises: 7a89b68e13ad
Create Date: 2025-07-26 13:37:38.488886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8e89f994fb'
down_revision = '7a89b68e13ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('premium_end_date',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('premium_end_date',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
