"""empty message

Revision ID: 733cb744471b
Revises: 8285fa5ded34
Create Date: 2025-08-01 23:57:01.993135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733cb744471b'
down_revision = '8285fa5ded34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('platforms',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('platforms',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
