"""empty message

Revision ID: 74a4890de52a
Revises: e5d33b1981f5
Create Date: 2025-08-01 23:19:36.134340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a4890de52a'
down_revision = 'e5d33b1981f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platforms', sa.String(), nullable=False))
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('platforms')

    # ### end Alembic commands ###
