"""empty message

Revision ID: 7a89b68e13ad
Revises: 0763d677d453
Create Date: 2025-07-26 13:24:16.286593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a89b68e13ad'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('premium_end_date', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('premium_end_date')
        batch_op.drop_column('premium')
        batch_op.drop_column('points')
        batch_op.drop_column('level')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
