"""empty message

Revision ID: 7acadd43e23e
Revises: 95de2246ea34
Create Date: 2025-08-05 19:41:20.423326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acadd43e23e'
down_revision = '95de2246ea34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videojuego_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('game_team_game_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'videojuego', ['videojuego_id'], ['id'])
        batch_op.drop_column('game_id')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('game_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_team_game_id_fkey', 'videojuego', ['game_id'], ['id'])
        batch_op.drop_column('videojuego_id')

    # ### end Alembic commands ###
