"""empty message

Revision ID: 8285fa5ded34
Revises: 74a4890de52a
Create Date: 2025-08-01 23:49:56.926570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8285fa5ded34'
down_revision = '74a4890de52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
