"""Recreate team table

Revision ID: 83ff94d2860b
Revises: 9f2b0e531823
Create Date: 2025-08-06 16:41:31.876832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ff94d2860b'
down_revision = '9f2b0e531823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('game_team', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    with op.batch_alter_table('team_tournament', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('team_tournament', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('game_team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('team')
    # ### end Alembic commands ###
