"""empty message

Revision ID: 954432aa52f6
Revises: 733cb744471b
Create Date: 2025-08-02 00:24:25.353437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954432aa52f6'
down_revision = '733cb744471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
