"""empty message

Revision ID: 95de2246ea34
Revises: 954432aa52f6
Create Date: 2025-08-05 19:28:31.684290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95de2246ea34'
down_revision = '954432aa52f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['videojuego.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('user_videojuego', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_videojuego', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user_team', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('game_team')
    # ### end Alembic commands ###
