"""empty message

Revision ID: 9f2b0e531823
Revises: 447dd214d1f6
Create Date: 2025-08-06 16:28:10.216415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2b0e531823'
down_revision = '447dd214d1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videojuego_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'videojuego', ['videojuego_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('videojuego_id')

    # ### end Alembic commands ###
