"""empty message

Revision ID: ade7e4082f4b
Revises: ba2c8d3eba22
Create Date: 2025-07-30 17:49:27.967417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade7e4082f4b'
down_revision = 'ba2c8d3eba22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.String(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_videojuego')
    # ### end Alembic commands ###
