"""empty message

Revision ID: e5d33b1981f5
Revises: 85d363ba11ff
Create Date: 2025-08-01 23:08:13.163315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d33b1981f5'
down_revision = '85d363ba11ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=False))
        batch_op.drop_column('videojuegos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videojuegos', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('release_date')
        batch_op.drop_column('platform')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
